### ISSUE TITLE
[BUG] Qb-Phone Not Opening

### ISSUE THREAD

**Issue by Jurajos** [qbcore-framework/qb-phone#325]
**Describe the bug**
Hi, Im pressing "M" For open qb-phone and not opening. I have full Qb-Pack. And In the console, not showing error.. 
And nothing... 

Can somebody help?

**Comment by sinphoenix** [comment]
have you tried to replace the resource?

Maybe check keybinds.. if you were in another server your key bind could be set to that keybind

**Comment by Getpwnedbydolbajoba** [comment]
Is your issue solved now? if it it is then please close your issue, thanks. :)

**Comment by RedxNy** [comment]
having the same issue, i attempted updating to a newer version however it still does not open nor errors once restarted.

**Comment by aecy** [comment]
If you press M and doesnt work, press . or ; or , to check

Sorry, im maybe late
