### ISSUE TITLE
message

### ISSUE THREAD

**Issue by cienar** [qbcore-framework/qb-phone#34]
if person is not in your contact list you cant message him, when you send message he doesnt see the message and notification.

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-phone/commit/8774bac6f55ccc88c162ee08c5b6af9a672238d6
Should be fixed with this commit, let me know if it does

**Comment by cienar** [comment]
worked babe

**Comment by cienar** [comment]
1 more issue when he saves my number after i messaged him in app its still shows number  not name
